language: node_js

node_js:
  - 0.10

env:
  global:
    - secure: nQDOPzSLiVUwgx/MgZiJczvhC/QJbKTZuqXabd/V5W8vgMVBcP00jsH/MRplh30nm/iwat7ts6CEXjcUnpDOzu5iHWi0wRD8cyD6loWBvzEk3DLAIzG0aMggV3l1VHqHKj+MO3+3CZMorTAFit7P5bKpufRj6W44InqSfDwhkwk=
    - secure: Kkes/5Hirc7wmSW3O/h83WG09BqccgL2aFTQNY2F5LEk1Vw5quADErKf0vB0JE15bfa1kFfAlrHRonMHV+w1MVypGePRtbIfNfGlYczcwhmFYYGoZY0mh9SbgYMxagJYK0gLA94Z91yMOCys1hz87IG7FjSHePelnZwz/h/ZX1E=

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install -g eslint jscs jshint

after_success:
  - npm install codeclimate-test-reporter coveralls
  - ./node_modules/.bin/istanbul cover --report lcovonly ./node_modules/.bin/karma -- start ./test/karma.conf.js --single-run
  - cat ./coverage/lcov.info | ./node_modules/.bin/codeclimate
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
