language: node_js

node_js:
  - 4

sudo: false

env:
  global:
    # CODECLIMATE_REPO_TOKEN
    - secure: nQDOPzSLiVUwgx/MgZiJczvhC/QJbKTZuqXabd/V5W8vgMVBcP00jsH/MRplh30nm/iwat7ts6CEXjcUnpDOzu5iHWi0wRD8cyD6loWBvzEk3DLAIzG0aMggV3l1VHqHKj+MO3+3CZMorTAFit7P5bKpufRj6W44InqSfDwhkwk=
    # COVERALLS_REPO_TOKEN
    - secure: A8QcfWUTAQHzjHV3/bxQwrO6+wlsAl/MAI/DAnbWtM37Z1Cwo6GfdxyP3dYMlz3TPNPvcRVpdwNzi5coenrIURgddPITXOy+Z/2Q8aWF9CQQaLxgaheFqGjZ8rh6CEUGZ6n0s38dv+mTB3xrvNPXLntARZmc1LwylGxWWxVIzFM=

cache:
  directories:
    - node_modules

before_install:
  - npm install --global npm@^3.5.3
  - npm install --global eslint@^1.10.3 jscs@^2.7.0 write-good@^0.9.1 nsp@^2.2.0
  - npm install --global karma-cli@^0.1.2

before_script:
  - npm install karma-firefox-launcher@^0.1.7 karma-phantomjs-launcher@^0.2.2 phantomjs@^1.9.19
  - export KARMA_BROWSERS=Firefox,PhantomJS
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

after_success:
  - npm install codeclimate-test-reporter@^0.1.1 coveralls@^2.11.6
  - ./node_modules/.bin/istanbul cover --report lcovonly ./node_modules/.bin/karma -- start ./test/karma.conf.js --single-run
  - cat ./coverage/lcov.info | ./node_modules/.bin/codeclimate-test-reporter
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls

deploy:
  - provider: npm
    email: rs@ruslansagitov.name
    api_key:
      secure: DcjSlEWCWFBbhLulXGEYyIB2/U+4zIlfpNH8D1iWscwGYwJMEgg14AxXcots0AXhZqXCK1TW/7WdoW2slsv688DhzxwS2zrqRcDqfZs6dLfo9JzeRSd3ZvJ0udVs2I2bjRZ2rxefCIOtQxuHF5AFlGCMvXmbr9+l0jmtMjE9tFI=
    on:
      all_branches: true
      tags: true
      repo: ruslansagitov/karma-loud
