language: node_js

node_js:
  - 0.12

sudo: false

env:
  global:
    # CODECLIMATE_REPO_TOKEN
    - secure: nQDOPzSLiVUwgx/MgZiJczvhC/QJbKTZuqXabd/V5W8vgMVBcP00jsH/MRplh30nm/iwat7ts6CEXjcUnpDOzu5iHWi0wRD8cyD6loWBvzEk3DLAIzG0aMggV3l1VHqHKj+MO3+3CZMorTAFit7P5bKpufRj6W44InqSfDwhkwk=
    # COVERALLS_REPO_TOKEN
    - secure: A8QcfWUTAQHzjHV3/bxQwrO6+wlsAl/MAI/DAnbWtM37Z1Cwo6GfdxyP3dYMlz3TPNPvcRVpdwNzi5coenrIURgddPITXOy+Z/2Q8aWF9CQQaLxgaheFqGjZ8rh6CEUGZ6n0s38dv+mTB3xrvNPXLntARZmc1LwylGxWWxVIzFM=

before_install:
  - npm install --global eslint@^0.21.2 jscs@^1.13.1 write-good@^0.9.1
  - npm install --global karma-cli@^0.0.4

before_script:
  - npm install karma-firefox-launcher@^0.1.6 karma-phantomjs-launcher@^0.1.4
  - export KARMA_BROWSERS=Firefox,PhantomJS
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

after_success:
  - npm install codeclimate-test-reporter@^0.0.4 coveralls@^2.11.2
  - ./node_modules/.bin/istanbul cover --report lcovonly ./node_modules/.bin/karma -- start ./test/karma.conf.js --single-run
  - cat ./coverage/lcov.info | ./node_modules/.bin/codeclimate
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls

deploy:
  - provider: npm
    email: rs@ruslansagitov.name
    api_key:
      secure: WDql4nGZUP2PAngl6ixvLDBRj57GwdvWrVEu9PLhwTvGaN36PagiPdnUW0VIkPn6XxR8X9MpghqYrbyRG3Qg4iYi6SOJ2hwr6IVUROcVOWK7iaDev3PlIHUlnknXXpfTtRv1EOsSjDfsOj/s4jP4q1jBo29DmGTrpaPbO3vbeMU=
    on:
      all_branches: true
      tags: true
      repo: ruslansagitov/karma-loud
